### ISSUE TITLE
some issues in "the IVy language" doc

### ISSUE THREAD

**Issue by erniecohen** [microsoft/ivy#43]
- The expression syntax construction `e1 if p else e2` seems to be missing. This bit of syntax seems to be critical, as there is no other obvious way to update a non-Boolean function at many points at once.

- Another feature, `type this` appears in only one place, and without any explanation.

- There is reference to a nonexistent section on import "below" (and no explanation of import). It also mentions reducing the need to use `old` in monitors, without actually describing old.

- The even-odd example has bugs (e.g. `nat := 0`). It's probably a good idea to make documentation examples part of the build.

**Comment by kenmcmil** [comment]
Fixed by commit 2d93e1f.

By the way, I'm assuming you mean here that the if/else operator was missing from the language overview (now fixed). If there are problems with the operator itself, please let me know.

**Comment by erniecohen** [comment]
Since you mention it, I was surprised to find out (thanks to the documentation update) that conditional operators (unlike conditionals) are eager. Is there any good reason for them not to be lazy?

**Comment by kenmcmil** [comment]
Only that the semantics is simpler. I'll grant that this is a trap for the unwary.  Maybe it would be better to disallow calls with side effects in expressions, so that you have to be explicit about the order and conditions of side effects. That or switch to short-circuit evaluation to be consistent with other languages.
