### ISSUE TITLE
oddeven2.ivy (example from language manual) not working?

### ISSUE THREAD

**Issue by erniecohen** [microsoft/ivy#48]
When I try ivy_check on oddeven2.ivy (or on the text taken from the language manual), I get the following error message:

Isolate evens:
error: The verification condition is not in the fragment FAU.

The following terms may generate an infinite sequence of instantiations:
  
test.ivy: nat.even(N_a + 1)
    (position 0 is a function from nat to nat)

I tried reinstalling and still get the same error.

**Comment by kenmcmil** [comment]
Good point. That's actually the correct output, but I should mention in the language doc that Ivy won't actually let you run this example unless you use the command-line option `complete=fo` to turn off the fragment checker. The way you would really do this is to use an abstract datatype for the numbers, but that's not discussed until the next section.

**Comment by kenmcmil** [comment]
Fixed in commit 9dd1fea.

Changed assume/guarantee reasoning example in language intro to use interpreted arithmetic instead of axioms for odd and even. This makes the VC's quantifier-free so they are in the decidable fragment and we don't have to deal with the issue of decidability. 

By the way, it's instructive to try the odd/even example in Dafny. Notice that in Ivy, odd doesn't have to carry the invariant of even and vice-versa. Also notice that the clients of odd/even don't have to carry their invariants.
