### ISSUE TITLE
Multi-cast to struct

### ISSUE THREAD

**Issue by asgeir386** [microsoft/ivy#72]
When I model the German Cache Coherence Protocol in IVy I would like to multi-cast the invalidates to chan2 that is a struct 

I'm transcribing the German protocol as described in "SMT-Based Verification With DVF", by Goel et al. 

type msg_cmd = {empty,reqs,reqe,inv,invack,gnts,gnte} 
.. 
module noc_msg = { 
    individual m_cmd : msg_cmd 
    individual m_data : data 
} 
.. 
module noc_mod = { 
    instantiate chan1(P:proc) : noc_msg # requests 
    instantiate chan2(P:proc) : noc_msg 
    relation chan2_inv(P:proc) # invalidates 
    instantiate chan3(P:proc) : noc_msg # invacks 
} 

  export action recv_req(p:proc) = { 
        var others : bool; 

        others := d_state=shared & (exists P. shrset(P) & P~=p); 

.. 
} else if noc.chan1(p).m_cmd=reqe & d_state=shared & others { 
            d_state := locked; 

            noc.chan2_inv(P) := shrset(P) & P~=p; # multi-cast inval to all nodes that have bit set in shrset except p 
shrset(P) := P=p; 

noc.chan1(p).m_cmd := empty; 

ownerptr := p; 

-- 

Is it possible to eliminate chan2_inv and multi-cast to chan2?

**Comment by kenmcmil** [comment]
Yes, you can do that with an if/else expression. Here's an example:

```
#lang ivy1.7

type t = struct {
    foo : bool,
    bar : bool
}

type q

relation list(X:q)
function chan(X:q) : t

action a = {
    var msg : t;
    msg.foo := true;
    chan(X) := msg if list(X) else chan(X);
    assert list(X) -> chan(X).foo;
}

export a

```

**Comment by asgeir386** [comment]
When I change foo to be of type msg_cmd (mimicking German protocol here) everything still works when assertion on line 19 chan(X).foo=inv but a mangled CTI is produced when I instead have chan(X).foo=empty (I've pasted the CTI at the end). The fields of chan are not displayed

Could be IVy version issue (the one I'm using is downloaded 11/04 2019)

#lang ivy1.7
 2
 3type msg_cmd      = {empty,reqs,reqe,inv,invack,gnts,gnte}
 4
 5type t = struct {
 6    foo : msg_cmd,
 7    bar : bool
 8}
 9
10type q
11
12relation list(X:q)
13function chan(X:q) : t
14
15action a = {
16    var msg : t;
17    msg.foo := inv;
18    chan(X) := msg if list(X) else chan(X);
19    assert list(X) -> chan(X).foo=empty;
20}

---

 ivy_check diagnose=true debug=true trace=true t.ivy

    Isolate this:

        The following action implementations are present:
            t.ivy: line 15: implementation of a

        The following program assertions are treated as guarantees:
            in action a when called from the environment:
                t.ivy: line 19: guarantee ... FAIL
    searching for a small model... done

    Trace follows...
    ********************************************************************************
        foo(0) = inv
        __X = 0
        bar(0) = false
        list(0) = true
        loc:msg = 0
        chan(0) = 0
    t.ivy: line 17: foo(loc:msg) := inv
    t.ivy: line 18: chan(X) := (loc:msg if list(X) else chan(X))
    t.ivy: line 19: assert list(X) -> foo(chan(X)) = empty

**Comment by kenmcmil** [comment]
Traces with structs in them are a little hard to read. In this case, the functions `foo` and `bar` are the "destructors" of type `t` (in other words, if `X` is of type `t`, then `foo(X)` gives the value of the `foo` field of `X`).  In the trace, `chan(0) = 0` means that the value of `chan(0)` is a struct of type `t` with name `0`.  To find the fields of `0`, you look at the interpretations of the destructors `foo` and `bar`. In this case, the struct is `{foo:inv,bar:false}`. So now looking at the trace, at line 17, we assign `inv` to the foo field of `loc:msg`, where initially `loc:msg = 0`.  Since `foo(0)` is already `inv`, there is no change in `loc:msg`, so we still have `loc:msg = 0`. This is a bit tricky: if we had said `foo(msg) := empty`, then `loc:msg` would change to `1` (or some other struct `t`)  such that `foo(1) = empty`. That is, the struct names changes, but the destructor functions are immutable, because values are immutable in Ivy. The again in line 18, there is no state change, since we are assigning `chan(0) := inv` and we already have `chan(0) = inv` in the initial state. Then in line 19 the assertion is violated, because `chan(0) = 0` and `foo(0) = inv`. 

Anyway, this is obviously not an ideal way to represent traces -- it reflects the way that Ivy logically encodes the semantics of structs. It's not a big problem, though -- when you see a 'numeral' of a structure type in the trace, use the destructor functions to find the field values.
