### ISSUE TITLE
Nondeterministic Choice in ivy_to_cpp

### ISSUE THREAD

**Issue by landonjefftaylor** [microsoft/ivy#86]
I've created an IVy file initializing several variables to a nondeterministic choice from an enumerated list. The initialization  is below, and the files are attached in [corner_nw.zip](https://github.com/microsoft/ivy/files/4840802/corner_nw.zip)

```
\# lang ivy1.7

type zones = {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r}
type directions = {wait,north,east,south,west,drop}
type status = {ok,faulty,busy,edge}

var zone : zones
var trav : directions

var northLink : status
var eastLink : status
var southLink : status
var westLink : status
var destNE : bool

var routed : directions

object spec = {
  
  after init {
    routed := wait;
    zone := *;
    trav := *;
    assume (zone = c | zone = d | zone = e | zone = f | zone = o | zone = p | zone = r);
    assume trav ~= drop & trav ~= wait;
    northLink := edge;
    westLink  := edge;
    eastLink  := *; assume eastLink  ~= edge;
    southLink := *; assume southLink ~= edge;
  }
  
} #end spec 
```

When I run `ivy_to_cpp target=repl corner_nw.ivy`, it produces a working C++ model, just like in the ["Hello World"](http://microsoft.github.io/ivy/examples/helloworld.html) example. However, this model doesn't show nondeterministic choice. Rather than randomly choosing an option from the enumerated types (or even looping through all the possibilities), it only chooses option 0 from the list.

In examining the C++ file (attached: [corner_nw.zip](https://github.com/microsoft/ivy/files/4840802/corner_nw.zip)), it appears the issue is caused by the following function named `ivy_choose`:

```
int corner_nw::___ivy_choose(int rng,const char *name,int id) {
        return 0;
    }
```

When I modified the return value (to 3, for example), it returned a result produced as if the third option of each list was chosen. I'm wondering if this was an intentional feature in ivy_to_cpp, or if it is supposed to randomly or sequentially test every possibility.

**Comment by kenmcmil** [comment]
Nondeterministic assignment in Ivy was intended to model adversarial choice when modeling protocols. It isn't very useful though, since it doesn't lend itself well to refinement proofs. The more normal way to model an adversarial choice in Ivy is to make it an input parameter of an exported action.  

The Ivy compiler treats the `*` as a "don't care". That is, since the program is presumably proved correct for any value of the `*`, the compiler is free to choose whatever value it likes, which it turns out is zero. If you want to generated randomized runs of a program, there is a different way to do that. You can compile a randomized tester.  Here's an example:

```
#lang ivy1.7

type t = {a,b,c}

var x : t

export action show(z:t) returns (y:t) = {
    y := x;
    x := z;
}
```

The tester will first randomly initialize `x`. Then it will call `show` with random values of `z`. This updates `x` and outputs its old value. Here's an example run:

```
$ ivyc target=test random2.ivy
$ ./random2 seed=2
> show(c)
= a
> show(a)
= c
> show(a)
= a
> show(a)
= a
> show(a)
= a
> show(c)
= a
> show(a)
= c
> show(a)
= a
> show(c)
= a
> show(c)
= c
> show(c)
= c
> show(b)
= c
> show(c)
= b
```

With the command line parameter `seed` you can choose different random seeds and get different runs. Also, by putting a `before` requirement on the action, you can constrain the values that Ivy generates: 

```
before show {
    require x ~= b;
}
```

The idea is that you can automatically test an Ivy program by randomly generating inputs that satisfy its requirements. It's a bit like Haskell's QuickCheck, but it generates a sequence of inputs rather than a single input.
