### ISSUE TITLE
Creating Custom Ser or Deser objects for transmitting data over wire

### ISSUE THREAD

**Issue by prpr2770** [microsoft/ivy#87]
I was wondering if the IvY team could recommend the best way to proceed for handling serialization and deserialization of complex-message structures which are to be sent over the wire. 

As I understand it, there seems to be two methods: 
1. The QUIC protocol implementation, chooses to implement independent serializer/deserializer modules (`quic_ser.ivy` and ` 'quic_deser.ivy`). These are scripts that contain C++ codes embedded inside the ivy-codebase. 
2. Using Ivy language itself to create the encoder/decoder - as described in the networking branch of Ivy. 

I would like to explore both the ways to proceed. However, there seems to be very little documentation describing how the `quic_ser.ivy` and `quic_deser.ivy` scripts are structured. In particular, could we have a reference document that describes the way the a custom-serializer/deserializer can be built, for a message-structure that contains sub-types ( variants )? 
It may even help, if you could point out which specific existing scripts in the library, should be used for understanding this topic. 

On another note, the following script [pass_typeinfer.ivy](https://github.com/microsoft/ivy/blob/0b63effa3cf13cc49997215c1aeae87501aff432/ivy/ivy2/s2/pass_typeinfer.ivy) uses the following libraries

```
include ivylang
include logic
include error
include analysis
include typeinf
```
Under what scenarios would you recommend these libraries to be used? Is there a description of the functionality provided by these libraries? 

Thank you. I really appreciate your assistance in helping me learn to use this tool.

**Comment by kenmcmil** [comment]
The recommended way to make a custom serializer/deserializer is to write the code in Ivy, as in the networking examples. The Ivy compiler generates standard serializers and deserializers for all datatypes. For QUIC I wrote some C++ code that builds on this mechanism, but I wouldn't recommend this, as the interface is undocumented and likely to change, and also the code is hard to read and maintain. Actually, in quic_codec.ivy, there is a start on a decoder for QUIC frames in Ivy, which is tested against the existing frame encoder. 

The code in `pass_typeinfer.ivy` is part of the V2 Ivy compiler, which is written in Ivy, rather than Python. The included files you refer to are part of the V2 compiler and not the standard library. In those files you can see some examples of parsing, abstract syntax trees, and so on, that might be helpful. However, if you are more interested in handling binary packet formats, the networking examples are probably more applicable.
